### ISSUE TITLE
Enhancement request/assistance

### ISSUE THREAD

**Issue by chrismauck** [polosson/Plantt#2]
I have created a "project portal" and am able to simply pull all of my projects into the plantt scheduler... however, given 167 project returns (month prior to "today" through end of list) and numerous happening concurrently, the tool overlaps items and tops out at 15 rows. Any advice?

It should also be noted that I am using the tool for display of timelines only. I have disabled editing through the tool - for now - as all of the data entry to date is handled through project submission by digital Producers on my team. Thanks!

**Comment by PoloMaillardet** [comment]
I'm glad you found this tool useful. Thanks for your feedback !

If I well understand your problem, the events are stacked over the bottom of the timeline, and exceed its height ? If so, you may change your `$scope.nbLines` at a higher value. (see [an example here](https://github.com/polosson/Plantt/blob/master/example/js/example.js#L14) - at line 14).

**Comment by chrismauck** [comment]
Thank you for the expedient reply! I modified $scope.nbLines gradually originally and then even got crazy and made the number 300... still to no avail. I added some console logs to plantt.js to see what was being generated. If I add a console.log(filledLines) after [line 328](https://github.com/polosson/Plantt/blob/master/src/plantt.js#L328), it always returns 15 - which is the number of lines being rendered, even with $scope.nbLines set at 99 (which logs at 100 btw).

In the attached image you can see the bright green color task/event and then far to the right another small green section. This is the same task/event, the other items/events are simply overlaying the longer task/event.

![2017-06-12_15-46-24](https://user-images.githubusercontent.com/5150084/27054395-5b6e976c-4f86-11e7-9fe7-00162ff7d7ed.jpg)

**Comment by polosson** [comment]
(sorry for the profile change, I was logged in with the wrong one)

Indeed, the loop that calculate the number of lines really needs to be refactored in some way... I currently don't have enough time to maintain this project, but if you are able to do this in a better way, you'll be awesome. Thanks !

**Comment by chrismauck** [comment]
I'll take a closer look. Thanks for the quick replies and the tool!!
